/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Stack = {
  _id: string;
  _type: "stack";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  key?: string;
  icon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type ContactLink = {
  _id: string;
  _type: "contactLink";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  key?: string;
  name?: string;
  link?: string;
};

export type Snippet = {
  _id: string;
  _type: "snippet";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  text?: string;
};

export type Gallery = {
  _id: string;
  _type: "gallery";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type IssuingOrgReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "issuingOrg";
};

export type Certificate = {
  _id: string;
  _type: "certificate";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  issuingOrg?: IssuingOrgReference;
  title?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  link?: string;
};

export type IssuingOrg = {
  _id: string;
  _type: "issuingOrg";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  key?: string;
};

export type StackReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "stack";
};

export type ProjectStacks = Array<
  {
    _key: string;
  } & StackReference
>;

export type ProjectLinks = {
  _type: "projectLinks";
  demo?: string;
  github?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type ProjectDemo = {
  _type: "projectDemo";
  thumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  src?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
};

export type Writings = {
  _id: string;
  _type: "writings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  metadataImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  componentID?: string;
  slug?: Slug;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & Table)
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & Code)
  >;
  publishedAt?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title?: string;
  slug?: Slug;
  description?: string;
  favicon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  demo?: ProjectDemo;
  links?: ProjectLinks;
  stacks?: ProjectStacks;
};

export type SanityVideoMetadataPlayback = {
  _type: "sanity.videoMetadata.playback";
  policy?: string;
};

export type SanityVideoMetadata = {
  _type: "sanity.videoMetadata";
  duration?: number;
  framerate?: number;
  aspectRatio?: number;
  hasAudio?: boolean;
  codec?: string;
  bitrate?: number;
};

export type SanityVideoAsset = {
  _id: string;
  _type: "sanity.videoAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  creditLine?: string;
  metadata?: SanityVideoMetadata;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
};

export type SanityVideo = {
  _type: "sanity.video";
  asset?: unknown;
  media?: unknown;
};

export type Table = {
  _type: "table";
  rows?: Array<
    {
      _key: string;
    } & TableRow
  >;
};

export type TableRow = {
  _type: "tableRow";
  cells?: Array<string>;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Stack
  | SanityImageCrop
  | SanityImageHotspot
  | ContactLink
  | Snippet
  | Gallery
  | IssuingOrgReference
  | Certificate
  | IssuingOrg
  | StackReference
  | ProjectStacks
  | ProjectLinks
  | SanityFileAssetReference
  | ProjectDemo
  | Writings
  | Slug
  | Project
  | SanityVideoMetadataPlayback
  | SanityVideoMetadata
  | SanityVideoAsset
  | SanityVideo
  | Table
  | TableRow
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: STACKS_QUERY
// Query: *[_type=="stack"]{    name,    key,    icon {  asset->{    _ref,    _type,    url,    metadata {      lqip,      palette {        dominant {          background,          foreground        }      },      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  hotspot,  crop}  }
export type STACKS_QUERY_RESULT = Array<{
  name: string | null;
  key: string | null;
  icon: {
    asset: {
      _ref: null;
      _type: "sanity.imageAsset";
      url: string | null;
      metadata: {
        lqip: string | null;
        palette: {
          dominant: {
            background: string | null;
            foreground: string | null;
          } | null;
        } | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
}>;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: SNIPPETS_QUERY
// Query: *[_type=="snippet"] | order(orderRank) {    _id,    text  }
export type SNIPPETS_QUERY_RESULT = Array<{
  _id: string;
  text: string | null;
}>;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: CERTIFICATES_QUERY
// Query: *[_type=="certificate"] | order(orderRank) {    _id,    title,    "issuingOrg": issuingOrg -> name,    link  }
export type CERTIFICATES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  issuingOrg: string | null;
  link: string | null;
}>;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: GALLERY_QUERY
// Query: *[_type=="gallery"] | order(orderRank) {    title,    images[] {  asset->{    _ref,    _type,    url,    metadata {      lqip,      palette {        dominant {          background,          foreground        }      },      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  hotspot,  crop}  }
export type GALLERY_QUERY_RESULT = Array<{
  title: string | null;
  images: Array<{
    asset: {
      _ref: null;
      _type: "sanity.imageAsset";
      url: string | null;
      metadata: {
        lqip: string | null;
        palette: {
          dominant: {
            background: string | null;
            foreground: string | null;
          } | null;
        } | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
}>;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type=="project"] | order(orderRank) {    title,    "slug": slug.current,    description,    favicon {  asset->{    _ref,    _type,    url,    metadata {      lqip,      palette {        dominant {          background,          foreground        }      },      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  hotspot,  crop},    demo {      src {  asset->{    url  }},      thumbnail {  asset->{    _ref,    _type,    url,    metadata {      lqip,      palette {        dominant {          background,          foreground        }      },      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  hotspot,  crop}    },    links,    "stacks": stacks[] -> { name, key }  }
export type PROJECTS_QUERY_RESULT = Array<{
  title: string | null;
  slug: string | null;
  description: string | null;
  favicon: {
    asset: {
      _ref: null;
      _type: "sanity.imageAsset";
      url: string | null;
      metadata: {
        lqip: string | null;
        palette: {
          dominant: {
            background: string | null;
            foreground: string | null;
          } | null;
        } | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    alt: null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  demo: {
    src: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    thumbnail: {
      asset: {
        _ref: null;
        _type: "sanity.imageAsset";
        url: string | null;
        metadata: {
          lqip: string | null;
          palette: {
            dominant: {
              background: string | null;
              foreground: string | null;
            } | null;
          } | null;
          dimensions: {
            width: number | null;
            height: number | null;
            aspectRatio: number | null;
          } | null;
        } | null;
      } | null;
      alt: null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  } | null;
  links: ProjectLinks | null;
  stacks: Array<{
    name: string | null;
    key: string | null;
  }> | null;
}>;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: CONTACTS_QUERY
// Query: *[_type=="contactLink"] {    key,    name,    link  }
export type CONTACTS_QUERY_RESULT = Array<{
  key: string | null;
  name: string | null;
  link: string | null;
}>;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: WRITINGS_QUERY
// Query: *[_type=="writings"] | order(_createdAt desc) {    title,    "slug": slug.current,    description,  }
export type WRITINGS_QUERY_RESULT = Array<{
  title: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h1" | "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  slug: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
}>;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: WRITING_BY_SLUG_QUERY
// Query: *[_type=="writings" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    description,    "metaTitle": pt::text(title),    "metaDescription": pt::text(description),    metadataImage {  asset->{    _ref,    _type,    url,    metadata {      lqip,      palette {        dominant {          background,          foreground        }      },      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  hotspot,  crop},    componentID,    publishedAt,    body[] {      ...,      _type == "image" => {  asset->{    _ref,    _type,    url,    metadata {      lqip,      palette {        dominant {          background,          foreground        }      },      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  hotspot,  crop},      _type == "code" => {        code,        language,        filename      }    }  }
export type WRITING_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h1" | "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  slug: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  metaTitle: string;
  metaDescription: string;
  metadataImage: {
    asset: {
      _ref: null;
      _type: "sanity.imageAsset";
      url: string | null;
      metadata: {
        lqip: string | null;
        palette: {
          dominant: {
            background: string | null;
            foreground: string | null;
          } | null;
        } | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  componentID: string | null;
  publishedAt: string | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "code";
        language: string | null;
        filename: string | null;
        code: string | null;
        highlightedLines?: Array<number>;
      }
    | {
        asset: {
          _ref: null;
          _type: "sanity.imageAsset";
          url: string | null;
          metadata: {
            lqip: string | null;
            palette: {
              dominant: {
                background: string | null;
                foreground: string | null;
              } | null;
            } | null;
            dimensions: {
              width: number | null;
              height: number | null;
              aspectRatio: number | null;
            } | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string | null;
        caption?: string;
        _type: "image";
        _key: string;
      }
    | {
        _key: string;
        _type: "table";
        rows?: Array<
          {
            _key: string;
          } & TableRow
        >;
      }
  > | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type=="stack"]{\n    name,\n    key,\n    icon {\n  asset->{\n    _ref,\n    _type,\n    url,\n    metadata {\n      lqip,\n      palette {\n        dominant {\n          background,\n          foreground\n        }\n      },\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n}\n  }\n': STACKS_QUERY_RESULT;
    '\n  *[_type=="snippet"] | order(orderRank) {\n    _id,\n    text\n  }\n': SNIPPETS_QUERY_RESULT;
    '\n  *[_type=="certificate"] | order(orderRank) {\n    _id,\n    title,\n    "issuingOrg": issuingOrg -> name,\n    link\n  }\n': CERTIFICATES_QUERY_RESULT;
    '\n  *[_type=="gallery"] | order(orderRank) {\n    title,\n    images[] {\n  asset->{\n    _ref,\n    _type,\n    url,\n    metadata {\n      lqip,\n      palette {\n        dominant {\n          background,\n          foreground\n        }\n      },\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n}\n  }\n': GALLERY_QUERY_RESULT;
    '\n  *[_type=="project"] | order(orderRank) {\n    title,\n    "slug": slug.current,\n    description,\n    favicon {\n  asset->{\n    _ref,\n    _type,\n    url,\n    metadata {\n      lqip,\n      palette {\n        dominant {\n          background,\n          foreground\n        }\n      },\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n},\n    demo {\n      src {\n  asset->{\n    url\n  }\n},\n      thumbnail {\n  asset->{\n    _ref,\n    _type,\n    url,\n    metadata {\n      lqip,\n      palette {\n        dominant {\n          background,\n          foreground\n        }\n      },\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n}\n    },\n    links,\n    "stacks": stacks[] -> { name, key }\n  }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type=="contactLink"] {\n    key,\n    name,\n    link\n  }\n': CONTACTS_QUERY_RESULT;
    '\n  *[_type=="writings"] | order(_createdAt desc) {\n    title,\n    "slug": slug.current,\n    description,\n  }\n': WRITINGS_QUERY_RESULT;
    '\n  *[_type=="writings" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    "metaTitle": pt::text(title),\n    "metaDescription": pt::text(description),\n    metadataImage {\n  asset->{\n    _ref,\n    _type,\n    url,\n    metadata {\n      lqip,\n      palette {\n        dominant {\n          background,\n          foreground\n        }\n      },\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n},\n    componentID,\n    publishedAt,\n    body[] {\n      ...,\n      _type == "image" => {\n  asset->{\n    _ref,\n    _type,\n    url,\n    metadata {\n      lqip,\n      palette {\n        dominant {\n          background,\n          foreground\n        }\n      },\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  hotspot,\n  crop\n},\n      _type == "code" => {\n        code,\n        language,\n        filename\n      }\n    }\n  }\n': WRITING_BY_SLUG_QUERY_RESULT;
  }
}
